/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var Hub = kurentoClient.register.abstracts.Hub;


/**
 * Create an element
 *
 * @classdesc
 *  SelectableMixer interface. Hub that allows input selection per output
 *
 * @extends module:core/abstracts.Hub
 *
 * @constructor module:selectablemixer.SelectableMixer
 */
function SelectableMixer(){
  SelectableMixer.super_.call(this);
};
inherits(SelectableMixer, Hub);


/**
 * @alias module:selectablemixer.SelectableMixer.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
SelectableMixer.constructorParams = {
  mediaPipeline: {
    type: 'kurento.MediaPipeline',
    required: true
  }
};

/**
 * @alias module:selectablemixer.SelectableMixer.events
 *
 * @extends module:core/abstracts.Hub.events
 */
SelectableMixer.events = Hub.events;


/**
 * Checker for {@link module:selectablemixer.SelectableMixer}
 *
 * @memberof module:selectablemixer
 *
 * @param {external:String} key
 * @param {module:selectablemixer.SelectableMixer} value
 */
function checkSelectableMixer(key, value)
{
  if(!(value instanceof SelectableMixer))
    throw ChecktypeError(key, SelectableMixer, value);
};


module.exports = SelectableMixer;

SelectableMixer.check = checkSelectableMixer;
