/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var Hub = kurentoClient.register.abstracts.Hub;


/**
 * Create an element
 *
 * @classdesc
 *  SelectableMixer interface. Hub that allows input selection per output
 *
 * @extends module:core/abstracts.Hub
 *
 * @constructor module:selectablemixer.SelectableMixer
 */
function SelectableMixer(){
  SelectableMixer.super_.call(this);
};
inherits(SelectableMixer, Hub);


/**
 * @alias module:selectablemixer.SelectableMixer.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
SelectableMixer.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  }
};

/**
 * @alias module:selectablemixer.SelectableMixer.events
 *
 * @extends module:core/abstracts.Hub.events
 */
SelectableMixer.events = Hub.events;


/**
 * Checker for {@link module:selectablemixer.SelectableMixer}
 *
 * @memberof module:selectablemixer
 *
 * @param {external:String} key
 * @param {module:selectablemixer.SelectableMixer} value
 */
function checkSelectableMixer(key, value)
{
  if(!(value instanceof SelectableMixer))
    throw ChecktypeError(key, SelectableMixer, value);
};


module.exports = SelectableMixer;

SelectableMixer.check = checkSelectableMixer;
